### PR TITLE
Add Batch Converting Feature for RVC-GUI

### PR DESCRIPTION
**Pull request by ghost**
Description:
As a user of RVC-GUI, I have been using the tool to convert audio recordings using the powerful RVC voice models. However, I encounter difficulties when working with long audio files on less powerful computers. To overcome this, I manually split long recordings into approximately 5-6 minute segments and convert them one by one. After each segment is processed (which takes about 5-10 minutes), I have to manually select the next segment for conversion. This process becomes time-consuming and repetitive, especially when working with multiple audio segments.

I propose the addition of a new feature to RVC-GUI - "Batch Converting." This feature would allow users to select multiple audio recordings as a list and have the program automatically convert them sequentially. For instance, if there are three audio segments in the list, RVC-GUI should convert the first segment and then automatically proceed to the next one until all the listed segments are processed.

Benefits of Batch Converting Feature:
1. Increased Efficiency: Users can save time and effort by avoiding manual intervention between each conversion task.
2. Improved User Experience: The batch converting feature simplifies the process, making it more user-friendly, especially for those dealing with multiple audio segments.
3. Resource Management: Users with less powerful computers can better manage their system resources, as they won't need to keep the entire long recording loaded in memory.

I believe that implementing the "Batch Converting" feature will greatly enhance the usability and productivity of RVC-GUI. This addition will be highly beneficial for users dealing with long audio recordings and improve the overall user experience of the tool. Thank you for considering my request.

### CODE REVIEW

**Comment by ghost** [comment]
This is not a merge request. This is actually a Issue request.

**Comment by ImRlyQt** [comment]
nie działa

**Comment by ghost** [comment]
> nie działa 

This is not a merge request. This is actually a Issue request.

**Comment by flavinho1983** [comment]
I downloaded the application, would like to know how to apply the updates? Do I have to download it and what is the next step?
Would you like to know how to include more voice models within the application?
Could you help?

**Pull request closed without merging**
